server:
  port: 8082
security:
  oauth2:
    client:
      client-id: codercuy-client
      client-secret: strong-secret
      scope:
        - read
        - write
springdoc:
  paths-to-exclude: /swagger-resources/**
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:cakemgr
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
